Updates to files and twaeks in main

diff --git a/Main b/Main
--- a/Main
+++ b/Main
@@ -13,6 +13,10 @@ VERSION="1.5" # ( Developers Use Only )
 XDALINK="http://forum.xda-developers.com/showthread.php?t=3176652"
 CUSER="$(whoami)"
 TOOLSDIR="$current/tools/tools"
+GITHUBLINK="https://github.com/Carloss32/Bongs_Multi_Kitchen_Linux.git"
+AUTOUPDATE="1" # Defines if we should turn on auto updates, if available
+GITHUBBRANCH="master"
+NEEDEDGIT="1.9"
 ## APK Kitchen Initial Variables ##
 APKKITCH=$current/APK_Kitchen
 export decompile="Sources_and_Resources_Files"
@@ -40,10 +44,17 @@ TOOLS=(which whoami basename dirname gcc java perl sed cut wget od wc cpio zip u
 TEMPDIR="$RKITCH/TEMP"
 ACTIVE_PROJECT=""
 ALIGN=4
-GITHUBLINK="https://github.com/Carloss32/Bongs_Multi_Kitchen_Linux.git"
-AUTOUPDATE="1" # Defines if we should turn on auto updates, if available
-GITHUBBRANCH="master"
-NEEDEDGIT="1.9"
+CBIN="" # Ramdisk compression method
+DBIN="" # Ramdisk decompression method
+META_INF="META-INF/com/google/android"
+UPDATER_SCRIPT_HEAD="updater-script-00_HEAD" # Unused
+UPDATER_SCRIPT_SYMLINKS="updater-script-10_SYMLINKS"
+UPDATER_SCRIPT_PERMISSIONS="updater-script-20_PERMISSIONS"
+UPDATER_SCRIPT_EXEC="updater-script-80_EXEC" # Unused
+UPDATER_SCRIPT_USER="updater-script-85_USER" # Unused
+UPDATER_SCRIPT_KERNEL="updater-script-90_KERNEL"
+UPDATER_SCRIPT_MODEM="updater-script-91_MODEM"
+UPDATER_SCRIPT_TAIL="updater-script-99_TAIL" # Unused
 
 
 BASE_MENU() {
@@ -83,7 +94,7 @@ echo -n "   Enter option: "
 		3) echo "Not Set By Developer Yet..: '$opt'"
 			sleep 1s
 			BASE_MENU
-		;; 
+		;;
 		99) clear; EXIT_OUT;;
 		*)
 			echo "Unknown command: '$opt'"
@@ -93,9 +104,6 @@ echo -n "   Enter option: "
     esac
 done
 }
-
-
-
 
 #####################################################################################
 #
@@ -128,50 +136,13 @@ else
 	framfol=$current/$rombase/system/framework
 	appfol=$current/$rombase/system/app
 	pappfol=$current/$rombase/system/priv-app
-	ARCH_TEST
 fi
-}
-
-ARCH_TEST() {
-arch=""
-arch2=""
-cd $framfol
-export armarch=$(ls -d */ | sed 's/\///' | grep -m 1 arm$)
-export arm64arch=$(ls -d */ | sed 's/\///' | grep -m 1 arm64$)
-export x86arch=$(ls -d */ | sed 's/\///' | grep -m 1 x86$)
-export x86_64arch=$(ls -d */ | sed 's/\///' | grep -m 1 x86_64$)
-if [[ $arm64arch = "arm64" && -f $framfol/arm64/boot.oat ]]; then	
-	export arch="arm64"
-	export odexst="Odexed"
-	if [[ $armarch = "arm" && -f $framfol/arm/boot.oat ]]; then 
-		export arch2="arm"
-		export odexst="Odexed"
-	fi
-elif [[ $x86_64arch = "x86_64" && -f $framfol/x86_64/boot.oat ]]; then	
-	export arch="x86_64"
-	export odexst="Odexed"
-	if [[ $x86arch = "x86" && -f $framfol/x86/boot.oat ]]; then 
-		export arch2="x86"
-		export odexst="Odexed"
-	fi
-elif [[ $armarch = "arm" && -f $framfol/$armarch/boot.oat ]]; then
-	export arch="arm"
-	export odexst="Odexed"
-elif [[ $x86arch = "x86" && -f $framfol/$x86arch/boot.oat ]]; then
-	export arch="x86"
-	export odexst="Odexed"
-	else
-		export odexst="De-Odexed"
-		export arch="De-Odexed"
-		export arch2="De-Odexed"
-		
-	fi
-DEODEX_START_MENU
 }
 
 DEODEX_START_MENU() {
 while :; do
 clear
+ARCH_TEST
 echo "----------------------------------------------------------------------------------------------------------------------"
 echo " MM. To Main Menu                            BONGS LOLLIPOP DEODEXER                                   "
 echo "----------------------------------------------------------------------------------------------------------------------"
@@ -209,6 +180,50 @@ echo -n "   Enter option: "
 		;;
     esac
 done
+}
+
+ARCH_TEST() {
+if [ -z "$rombase" ]; then
+arch=""
+arch2=""
+export odexst=""
+export arch=""
+export arch2=""
+else
+arch=""
+arch2=""
+cd $framfol
+export armarch=$(ls -d */ | sed 's/\///' | grep -m 1 arm$)
+export arm64arch=$(ls -d */ | sed 's/\///' | grep -m 1 arm64$)
+export x86arch=$(ls -d */ | sed 's/\///' | grep -m 1 x86$)
+export x86_64arch=$(ls -d */ | sed 's/\///' | grep -m 1 x86_64$)
+if [[ $arm64arch = "arm64" && -f $framfol/arm64/boot.oat ]]; then
+	export arch="arm64"
+	export odexst="Odexed"
+	if [[ $armarch = "arm" && -f $framfol/arm/boot.oat ]]; then 
+		export arch2="arm"
+		export odexst="Odexed"
+	fi
+elif [[ $x86_64arch = "x86_64" && -f $framfol/x86_64/boot.oat ]]; then	
+	export arch="x86_64"
+	export odexst="Odexed"
+	if [[ $x86arch = "x86" && -f $framfol/x86/boot.oat ]]; then 
+		export arch2="x86"
+		export odexst="Odexed"
+	fi
+elif [[ $armarch = "arm" && -f $framfol/$armarch/boot.oat ]]; then
+	export arch="arm"
+	export odexst="Odexed"
+elif [[ $x86arch = "x86" && -f $framfol/$x86arch/boot.oat ]]; then
+	export arch="x86"
+	export odexst="Odexed"
+	else
+		export odexst="De-Odexed"
+		export arch="De-Odexed"
+		export arch2="De-Odexed"
+		
+	fi
+fi
 }
 
 DEODEX_SEL_MENU() {
@@ -2216,6 +2231,36 @@ PATH="$PATH:$PWD/tools/tools/adb"
 PATH="$PATH:$PWD/tools/tools/zipalign"
 export PATH
 
+# Cleaning
+unset CROSS_COMPILE # We're not cross-compiling anything here and it may cause problems with some makefiles
+
+# Before we begin, make sure that all our tools are available
+if [[ "$(which "${TOOLS[@]}" >/dev/null; echo $?)" -ne 0 ]]; then
+	MISSINGTOOLS=""
+	for TOOL in "${TOOLS[@]}"; do
+		if [[ -z "$(which $TOOL)" ]]; then
+			MISSINGTOOLS+=" $TOOL"
+		fi
+	done
+	echo "It looks like you don't have required tool(s):$MISSINGTOOLS"
+	echo "This check was made through 'which' command"
+	echo "Please install missing tool(s) and launch kitchen again"
+	exit 1
+fi
+echo
+
+# Check if symlink support is present
+if [[ "$(ln -s Bong Bong.ln.test >/dev/null 2>&1; echo $?)" -ne 0 ]]; then
+	echo "ERROR: Current kitchen location doesn't support symbolic links!"
+	echo "Symbolic links cannot be used on Windows-based filesystems, such as FAT, NTFS, or VirtualBox shared folder mount on one of the previous"
+	echo "You must use BongsMultiKitchen in native Linux location, such as /root, /home/username, /tmp, or any other mountpoint, which supports symbolic links"
+	exit 1
+else
+	rm -f Bong.ln.test
+fi
+
+# Create our temporary directory
+mkdir -p "$TEMPDIR"
 
 ## Test for Tools And Throw Error If Any Missing ##
 ERROR="0"
